- name: XRay-core with ShadowSocks and VLESS-XTLS-uTLS-Reality service
  hosts: all
  become: true

  vars:
    os_user: "xray"
    shadowsocks_port: 8000
    shadowsocks_method: "aes-128-gcm"
    vless_port: 9000
    vless_sni: "www.microsoft.com"

  tasks:

    - name: Create service user
      ansible.builtin.user:
        name: "{{ os_user }}"
        home: "/home/{{ os_user }}"
        shell: "/bin/false"
        password: "!"

    - name: Install QR encoder
      ansible.builtin.apt:
        name: qrencode
        state: present
        update_cache: true

    - name: Deploy XRay-core binaries
      ansible.builtin.unarchive:
        remote_src: true
        src: "https://github.com/XTLS/Xray-core/releases/latest/download/Xray-{{ os_host }}-{{ arch_host }}.zip"
        dest: "/home/{{ os_user }}"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"

    - name: Set binary +x
      ansible.builtin.file:
        path: "/home/{{ os_user }}/xray"
        mode: "0755"

    - name: Generate ShadowSocks password
      ansible.builtin.set_fact:
        shadowsocks_password: "{{ range(10000000, 99999999) | random | to_uuid }}"

    - name: Generate VLESS IDs
      ansible.builtin.set_fact:
        vless_client_id: "{{ range(10000000, 99999999) | random | to_uuid }}"
        vless_short_id: "{{ range(10000000, 99999999) | random }}"

    - name: Generate X25519 pair
      ansible.builtin.command: "/home/{{ os_user }}/xray x25519"
      changed_when: false
      register: "x25519"

    - name: Set X25519 pair
      ansible.builtin.set_fact:
        vless_private_key: "{{ x25519.stdout[12:55] }}"
        vless_public_key: "{{ x25519.stdout[66:109] }}"

    - name: Deploy XRay configuration
      ansible.builtin.template:
        src: "config.json.j2"
        dest: "/home/{{ os_user }}/config.json"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "0640"

    - name: Deploy systemd unit
      ansible.builtin.template:
        src: "xray.service.j2"
        dest: "/etc/systemd/system/xray.service"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Enable and start service
      ansible.builtin.systemd:
        name: "xray.service"
        daemon_reload: true
        state: "started"
        enabled: true

    - name: Compose ShadowSocks link
      ansible.builtin.set_fact:
        shadowsocks_link: "ss://{{ shadowsocks_method }}:{{ shadowsocks_password }}@{{ ansible_host }}:{{ shadowsocks_port }}#{{ inventory_hostname }}"

    - name: Compose VLESS link
      ansible.builtin.set_fact:
        vless_link: "vless://{{ vless_client_id }}@{{ ansible_host }}:{{ vless_port }}?security=reality&encryption=none&pbk={{ vless_public_key }}&headerType=none&fp=chrome&type=tcp&flow=xtls-rprx-vision&sni={{ vless_sni }}&sid={{ vless_short_id }}#{{ inventory_hostname }}"

    - name: Generate ShadowSocks QR
      ansible.builtin.command: "qrencode -t PNG -o /home/{{ os_user }}/shadowsocks.png \"{{ shadowsocks_link }}\""
      changed_when: false

    - name: Set owner shadowsocks.png
      ansible.builtin.file:
        path: "/home/{{ os_user }}/shadowsocks.png"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "0640"

    - name: Fetch ShadowSocks QR
      ansible.builtin.fetch:
        src: "/home/{{ os_user }}/shadowsocks.png"
        dest: "shadowsocks.png"
        flat: true

    - name: Generate VLESS QR
      ansible.builtin.command: "qrencode -t PNG -o /home/{{ os_user }}/vless.png \"{{ vless_link }}\""
      changed_when: false

    - name: Set owner vless.png
      ansible.builtin.file:
        path: "/home/{{ os_user }}/vless.png"
        owner: "{{ os_user }}"
        group: "{{ os_user }}"
        mode: "0640"

    - name: Fetch VLESS QR
      ansible.builtin.fetch:
        src: "/home/{{ os_user }}/vless.png"
        dest: "vless.png"
        flat: true

    - name: Display ShadowSocks configuration
      ansible.builtin.debug:
        msg: "Shadowsocks link: {{ shadowsocks_link }}"

    - name: Display VLESS configuration
      ansible.builtin.debug:
        msg: "VLESS link: {{ vless_link }}"
